# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

labels:
  # Default GitHub labels
  - color: d73a4a
    name: bug
    description: Something isn't working
  - color: cfd3d7
    name: duplicate
    description: This issue or pull request already exists
  - color: a2eeef
    name: enhancement
    description: New feature or request
  - color: 7057ff
    name: good first issue
    description: Good for newcomers
  - color: 008672
    name: help wanted
    description: Extra attention is needed
  - color: e4e669
    name: invalid
    description: This doesn't seem right
  - color: d876e3
    name: question
    description: Further information is requested
  - color: ffffff
    name: wontfix
    description: This will not be worked on
  
  # Labels specific to cloudalchemy
  - color: 0366d6
    name: area/docs
    description: Improvements or additions to documentation
  - color: 0366d6
    name: area/tests
    description: Everything related to molecule tests and linters
  - color: 0366d6
    name: area/automation
    description: Bots, bots everywhere
  - color: 0366d6
    name: area/vars
    description: Ansible variables used in role
  - color: 0366d6
    name: area/tasks
    description: Logic behind ansible role
  - color: 0366d6
    name: area/jinja
    description: Templates

branches:
  - name: master
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: false
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: false
        # Required. The list of status checks to require in order to merge into this branch
        contexts:
        # - "WIP"
        - "ci/circleci: lint"
        - "ci/circleci: test-2.9"
        - "ci/circleci: test-2.10"
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
